// Squig.link domain configuration
// Each domain hosts phone_book.json and data/{filename} L.txt files

export interface DomainConfig {
  name: string;      // Identifier
  domain?: string;   // Base domain (e.g. "hbb.squig.link")
  fullUrl?: string;  // Override URL for phone_book.json
  quality: 'high' | 'low';
}

export const SQUIGLINK_DOMAINS: DomainConfig[] = [
  // Overrides (High Quality / Specific Paths)
  { name: 'crinacle', fullUrl: 'https://graph.hangout.audio/iem/711/data/phone_book.json', quality: 'high' },
  { name: 'crinacle5128', fullUrl: 'https://graph.hangout.audio/iem/5128/data/phone_book.json', quality: 'high' },
  { name: 'earphonesarchive', domain: 'earphonesarchive.squig.link', quality: 'high' },
  { name: 'sai', domain: 'sai.squig.link', quality: 'high' },
  
  // Overrides (Standard)
  { name: 'superreview', fullUrl: 'https://squig.link/data/phone_book.json', quality: 'low' },
  { name: 'den-fi', fullUrl: 'https://ish.squig.link/data/phone_book.json', quality: 'low' },
  { name: 'paulwasabii', fullUrl: 'https://pw.squig.link/data/phone_book.json', quality: 'low' },
  { name: 'listener5128', fullUrl: 'https://listener800.github.io/5128/data/phone_book.json', quality: 'low' },
  { name: 'crinacleHP', fullUrl: 'https://graph.hangout.audio/hp/data/phone_book.json', quality: 'low' },

  // Standard Subdomains (Will be probed for /data/phone_book.json, /iems/..., etc.)
  { name: 'hbb', domain: 'hbb.squig.link', quality: 'low' },
  { name: 'precog', domain: 'precog.squig.link', quality: 'low' },
  { name: 'timmyv', domain: 'timmyv.squig.link', quality: 'low' },
  { name: 'aftersound', domain: 'aftersound.squig.link', quality: 'low' },
  { name: 'vortexreviews', domain: 'vortexreviews.squig.link', quality: 'low' },
  { name: 'tonedeafmonk', domain: 'tonedeafmonk.squig.link', quality: 'low' },
  { name: 'rg', domain: 'rg.squig.link', quality: 'low' },
  { name: 'nymz', domain: 'nymz.squig.link', quality: 'low' },
  { name: 'gadgetrytech', domain: 'gadgetrytech.squig.link', quality: 'low' },
  { name: 'eliseaudio', domain: 'eliseaudio.squig.link', quality: 'low' },
  { name: 'achoreviews', domain: 'achoreviews.squig.link', quality: 'low' },
  { name: 'aden', domain: 'aden.squig.link', quality: 'low' },
  { name: 'adri-n', domain: 'adri-n.squig.link', quality: 'low' },
  { name: 'animagus', domain: 'animagus.squig.link', quality: 'low' },
  { name: 'ankramutt', domain: 'ankramutt.squig.link', quality: 'low' },
  { name: 'arc', domain: 'arc.squig.link', quality: 'low' },
  { name: 'atechreviews', domain: 'atechreviews.squig.link', quality: 'low' },
  { name: 'arn', domain: 'arn.squig.link', quality: 'low' },
  { name: 'audioamigo', domain: 'audioamigo.squig.link', quality: 'low' },
  { name: 'theaudiostore', domain: 'theaudiostore.squig.link', quality: 'low' },
  { name: 'awsmdanny', domain: 'awsmdanny.squig.link', quality: 'low' },
  { name: 'bakkwatan', domain: 'bakkwatan.squig.link', quality: 'low' },
  { name: 'banzai1122', domain: 'banzai1122.squig.link', quality: 'low' },
  { name: 'bassyalexander', domain: 'bassyalexander.squig.link', quality: 'low' },
  { name: 'bassaudio', domain: 'bassaudio.squig.link', quality: 'low' },
  { name: 'bedrock', domain: 'bedrock.squig.link', quality: 'low' },
  { name: 'boizoff', domain: 'boizoff.squig.link', quality: 'low' },
  { name: 'breampike', domain: 'breampike.squig.link', quality: 'low' },
  { name: 'bryaudioreviews', domain: 'bryaudioreviews.squig.link', quality: 'low' },
  { name: 'bukanaudiophile', domain: 'bukanaudiophile.squig.link', quality: 'low' },
  { name: 'csi-zone', domain: 'csi-zone.squig.link', quality: 'low' },
  { name: 'dchpgall', domain: 'dchpgall.squig.link', quality: 'low' },
  { name: 'dhrme', domain: 'dhrme.squig.link', quality: 'low' },
  { name: 'dl', domain: 'dl.squig.link', quality: 'low' },
  { name: 'doltonius', domain: 'doltonius.squig.link', quality: 'low' },
  { name: 'ducbloke', domain: 'ducbloke.squig.link', quality: 'low' },
  { name: 'ekaudio', domain: 'ekaudio.squig.link', quality: 'low' },
  { name: 'fahryst', domain: 'fahryst.squig.link', quality: 'low' },
  { name: 'enemyspider', domain: 'enemyspider.squig.link', quality: 'low' },
  { name: 'eplv', domain: 'eplv.squig.link', quality: 'low' },
  { name: 'flare', domain: 'flare.squig.link', quality: 'low' },
  { name: 'foxtoldmeso', domain: 'foxtoldmeso.squig.link', quality: 'low' },
  { name: 'freeryder05', domain: 'freeryder05.squig.link', quality: 'low' },
  { name: 'hadoe', domain: 'hadoe.squig.link', quality: 'low' },
  { name: 'harpo', domain: 'harpo.squig.link', quality: 'low' },
  { name: 'hore', domain: 'hore.squig.link', quality: 'low' },
  { name: 'hu-fi', domain: 'hu-fi.squig.link', quality: 'low' },
  { name: 'ianfann', domain: 'ianfann.squig.link', quality: 'low' },
  { name: 'ideru', domain: 'ideru.squig.link', quality: 'low' },
  { domain: 'iemocean.squig.link', name: 'iemocean', quality: 'low' },
  { name: 'iemworld', domain: 'iemworld.squig.link', quality: 'low' },
  { name: 'isaiahse', domain: 'isaiahse.squig.link', quality: 'low' },
  { name: 'jacstone', domain: 'jacstone.squig.link', quality: 'low' },
  { name: 'jaytiss', domain: 'jaytiss.squig.link', quality: 'low' },
  { name: 'joshtbvo', domain: 'joshtbvo.squig.link', quality: 'low' },
  { name: 'kazi', domain: 'kazi.squig.link', quality: 'low' },
  { name: 'kr0mka', domain: 'kr0mka.squig.link', quality: 'low' },
  { name: 'lestat', domain: 'lestat.squig.link', quality: 'low' },
  { name: 'listener', domain: 'listener.squig.link', quality: 'low' },
  { name: 'loomynarty', domain: 'loomynarty.squig.link', quality: 'low' },
  { name: 'lown-fi', domain: 'lown-fi.squig.link', quality: 'low' },
  { name: 'melatonin', domain: 'melatonin.squig.link', quality: 'low' },
  { name: 'mmagtech', domain: 'mmagtech.squig.link', quality: 'low' },
  { name: 'musicafe', domain: 'musicafe.squig.link', quality: 'low' },
  { name: 'obodio', domain: 'obodio.squig.link', quality: 'low' },
  { name: 'practiphile', domain: 'practiphile.squig.link', quality: 'low' },
  { name: 'pw', domain: 'pw.squig.link', quality: 'low' },
  { name: 'ragnarok', domain: 'ragnarok.squig.link', quality: 'low' },
  { name: 'recode', domain: 'recode.squig.link', quality: 'low' },
  { name: 'regancipher', domain: 'regancipher.squig.link', quality: 'low' },
  { name: 'riz', domain: 'riz.squig.link', quality: 'low' },
  { name: 'smirk', domain: 'smirk.squig.link', quality: 'low' },
  { name: 'soundignity', domain: 'soundignity.squig.link', quality: 'low' },
  { name: 'suporsalad', domain: 'suporsalad.squig.link', quality: 'low' },
  { name: 'tgx78', domain: 'tgx78.squig.link', quality: 'low' },
  { name: 'therollo9', domain: 'therollo9.squig.link', quality: 'low' },
  { name: 'scboy', domain: 'scboy.squig.link', quality: 'low' },
  { name: 'seanwee', domain: 'seanwee.squig.link', quality: 'low' },
  { name: 'silicagel', domain: 'silicagel.squig.link', quality: 'low' },
  { name: 'sl0the', domain: 'sl0the.squig.link', quality: 'low' },
  { name: 'soundcheck39', domain: 'soundcheck39.squig.link', quality: 'low' },
  { name: 'tanchjim', domain: 'tanchjim.squig.link', quality: 'low' },
  { name: 'tedthepraimortis', domain: 'tedthepraimortis.squig.link', quality: 'low' },
  { name: 'treblewellxtended', domain: 'treblewellxtended.squig.link', quality: 'low' },
  { name: 'vsg', domain: 'vsg.squig.link', quality: 'low' },
  { name: 'yanyin', domain: 'yanyin.squig.link', quality: 'low' },
  { name: 'yoshiultra', domain: 'yoshiultra.squig.link', quality: 'low' },
  { name: 'kuulokenurkka', domain: 'kuulokenurkka.squig.link', quality: 'low' },
];

export function isHighQualityDomain(name: string): boolean {
  const config = SQUIGLINK_DOMAINS.find(d => d.name === name || d.domain === name);
  return config?.quality === 'high';
}
