// Squig.link domain configuration
// Each domain hosts phone_book.json and data/{filename} L.txt files

export interface DomainConfig {
  domain: string;
  quality: 'high' | 'low';
  // Some domains may have different data directory structures
  dataDir?: string;
}

export const SQUIGLINK_DOMAINS: DomainConfig[] = [
  // High quality sources - trusted measurement rigs and methodology
  { domain: 'crinacle.squig.link', quality: 'high' },
  { domain: 'earphonesarchive.squig.link', quality: 'high' },
  { domain: 'sai.squig.link', quality: 'high' },
  
  // Standard quality sources
  { domain: 'squig.link', quality: 'low' },
  { domain: 'superreview.squig.link', quality: 'low' },
  { domain: 'bryaudio.squig.link', quality: 'low' },
  { domain: 'afteraudio.squig.link', quality: 'low' },
  { domain: 'bedrockreviews.squig.link', quality: 'low' },
  { domain: 'bregar.squig.link', quality: 'low' },
  { domain: 'eliseaudio.squig.link', quality: 'low' },
  { domain: 'eplv.squig.link', quality: 'low' },
  { domain: 'hiendportable.squig.link', quality: 'low' },
  { domain: 'paulwasabi.squig.link', quality: 'low' },
  { domain: 'precogvision.squig.link', quality: 'low' },
  { domain: 'recode.squig.link', quality: 'low' },
  { domain: 'rikudougoku.squig.link', quality: 'low' },
  { domain: 'tgx78.squig.link', quality: 'low' },
  { domain: 'vortexreviews.squig.link', quality: 'low' },
  { domain: 'vsg.squig.link', quality: 'low' },

  // Expanded sources
  { domain: 'hbb.squig.link', quality: 'low' },
  { domain: 'precog.squig.link', quality: 'low' },
  { domain: 'timmyv.squig.link', quality: 'low' },
  { domain: 'aftersound.squig.link', quality: 'low' },
  { domain: 'tonedeafmonk.squig.link', quality: 'low' },
  { domain: 'rg.squig.link', quality: 'low' },
  { domain: 'nymz.squig.link', quality: 'low' },
  { domain: 'gadgetrytech.squig.link', quality: 'low' },
  { domain: 'ish.squig.link', quality: 'low' }, // den-fi
  { domain: 'achoreviews.squig.link', quality: 'low' },
  { domain: 'aden.squig.link', quality: 'low' },
  { domain: 'adri-n.squig.link', quality: 'low' },
  { domain: 'animagus.squig.link', quality: 'low' },
  { domain: 'ankramutt.squig.link', quality: 'low' },
  { domain: 'arc.squig.link', quality: 'low' },
  { domain: 'atechreviews.squig.link', quality: 'low' },
  { domain: 'arn.squig.link', quality: 'low' },
  { domain: 'audioamigo.squig.link', quality: 'low' },
  { domain: 'theaudiostore.squig.link', quality: 'low' },
  { domain: 'awsmdanny.squig.link', quality: 'low' },
  { domain: 'bakkwatan.squig.link', quality: 'low' },
  { domain: 'banzai1122.squig.link', quality: 'low' },
  { domain: 'bassyalexander.squig.link', quality: 'low' },
  { domain: 'bassaudio.squig.link', quality: 'low' },
  { domain: 'bedrock.squig.link', quality: 'low' },
  { domain: 'boizoff.squig.link', quality: 'low' },
  { domain: 'breampike.squig.link', quality: 'low' },
  { domain: 'bryaudioreviews.squig.link', quality: 'low' },
  { domain: 'bukanaudiophile.squig.link', quality: 'low' },
  { domain: 'csi-zone.squig.link', quality: 'low' },
  { domain: 'dchpgall.squig.link', quality: 'low' },
  { domain: 'dhrme.squig.link', quality: 'low' },
  { domain: 'dl.squig.link', quality: 'low' },
  { domain: 'doltonius.squig.link', quality: 'low' },
  { domain: 'ducbloke.squig.link', quality: 'low' },
  { domain: 'ekaudio.squig.link', quality: 'low' },
  { domain: 'fahryst.squig.link', quality: 'low' },
  { domain: 'enemyspider.squig.link', quality: 'low' },
  { domain: 'flare.squig.link', quality: 'low' },
  { domain: 'foxtoldmeso.squig.link', quality: 'low' },
  { domain: 'freeryder05.squig.link', quality: 'low' },
  { domain: 'hadoe.squig.link', quality: 'low' },
  { domain: 'harpo.squig.link', quality: 'low' },
  { domain: 'hore.squig.link', quality: 'low' },
  { domain: 'hu-fi.squig.link', quality: 'low' },
  { domain: 'ianfann.squig.link', quality: 'low' },
  { domain: 'ideru.squig.link', quality: 'low' },
  { domain: 'iemocean.squig.link', quality: 'low' },
  { domain: 'iemworld.squig.link', quality: 'low' },
  { domain: 'isaiahse.squig.link', quality: 'low' },
  { domain: 'jacstone.squig.link', quality: 'low' },
  { domain: 'jaytiss.squig.link', quality: 'low' },
  { domain: 'joshtbvo.squig.link', quality: 'low' },
  { domain: 'kazi.squig.link', quality: 'low' },
  { domain: 'kr0mka.squig.link', quality: 'low' },
  { domain: 'lestat.squig.link', quality: 'low' },
  { domain: 'listener.squig.link', quality: 'low' },
  { domain: 'loomynarty.squig.link', quality: 'low' },
  { domain: 'lown-fi.squig.link', quality: 'low' },
  { domain: 'melatonin.squig.link', quality: 'low' },
  { domain: 'mmagtech.squig.link', quality: 'low' },
  { domain: 'musicafe.squig.link', quality: 'low' },
  { domain: 'obodio.squig.link', quality: 'low' },
  { domain: 'practiphile.squig.link', quality: 'low' },
  { domain: 'pw.squig.link', quality: 'low' },
  { domain: 'ragnarok.squig.link', quality: 'low' },
  { domain: 'regancipher.squig.link', quality: 'low' },
  { domain: 'riz.squig.link', quality: 'low' },
  { domain: 'smirk.squig.link', quality: 'low' },
  { domain: 'soundignity.squig.link', quality: 'low' },
  { domain: 'suporsalad.squig.link', quality: 'low' },
  { domain: 'therollo9.squig.link', quality: 'low' },
  { domain: 'scboy.squig.link', quality: 'low' },
  { domain: 'seanwee.squig.link', quality: 'low' },
  { domain: 'silicagel.squig.link', quality: 'low' },
  { domain: 'sl0the.squig.link', quality: 'low' },
  { domain: 'soundcheck39.squig.link', quality: 'low' },
  { domain: 'tanchjim.squig.link', quality: 'low' },
  { domain: 'tedthepraimortis.squig.link', quality: 'low' },
  { domain: 'treblewellxtended.squig.link', quality: 'low' },
  { domain: 'yanyin.squig.link', quality: 'low' },
  { domain: 'yoshiultra.squig.link', quality: 'low' },
  { domain: 'kuulokenurkka.squig.link', quality: 'low' },
];

export function isHighQualityDomain(domain: string): boolean {
  const config = SQUIGLINK_DOMAINS.find(d => d.domain === domain);
  return config?.quality === 'high';
}
